import {ApiConflictResponse} from '@nestjs/swagger';
import {ApiError} from '@/interfaces';

/**
 * 409 response decorator for Swagger autogenerated documentation.
 */
export const ConflictApiResponse = (description = 'Конфликт: невозможно создать ресурс или создаваемый ресурс уже существует'): MethodDecorator & ClassDecorator => ApiConflictResponse({
  description,
  type: ApiError,
});
