import {ApiErrorResponse} from '@/interfaces';
import {ApiForbiddenResponse} from '@nestjs/swagger';

/**
 * 403 response decorator for Swagger autogenerated documentation.
 */
export const ForbiddenApiResponse = (description = 'Недостаточно прав для выполнения операции'): MethodDecorator & ClassDecorator => ApiForbiddenResponse({
  description,
  type: ApiErrorResponse,
});
