import {ApiQuery} from '@nestjs/swagger';
import {LIMIT_PARAM} from '../../constants';

/**
 * Limit query parameter decorator for Swagger autogenerated documentation.
 */
export const LimitApiQuery = (): MethodDecorator => ApiQuery({name: LIMIT_PARAM, type: Number, required: false});
