import {ApiQuery} from '@nestjs/swagger';
import {PAGE_PARAM} from '@/constants';

/**
 * Page query parameter decorator for Swagger autogenerated documentation.
 */
export const PageApiQuery = (): MethodDecorator => ApiQuery({name: PAGE_PARAM, type: Number, required: false});
