import {ApiQuery} from '@nestjs/swagger';
import {SIZE_PARAM} from '../../constants';

/**
 * Size query parameter decorator for Swagger autogenerated documentation.
 */
export const SizeApiQuery = (): MethodDecorator => ApiQuery({name: SIZE_PARAM, type: Number, required: false});
