export const CACHE_SERVICE_OPTIONS = 'CACHE_SERVICE_OPTIONS';
export const DISCORD_SERVICE_OPTIONS = 'DISCORD_SERVICE_OPTIONS';
export const IP_WHITELIST_GUARD_OPTIONS = 'IP_WHITELIST_GUARD_OPTIONS';
export const VALIDATION_PIPE_OPTIONS = 'VALIDATION_PIPE_OPTIONS';

export const LIMIT_PARAM = 'limit';
export const OFFSET_PARAM = 'offset';
export const PAGE_PARAM = 'page';
export const SIZE_PARAM = 'size';
